trigger:
- master

pool:
  vmImage: windows-latest

name: $(Year:yy)$(DayOfYear)$(Rev:r)
steps:
- task: UseDotNet@2
  displayName: Ensure 5.0 SDK
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true

- script: dotnet build src\InheritDoc -c Dist --version-suffix ci$(Build.BuildNumber)
  displayName: Build

- script: dotnet test tests\InheritDoc.Test -c Coverage -s tests\runsettings --logger trx
  displayName: Test

- task: NuGetAuthenticate@0
  condition: ne(variables['Build.Reason'], 'PullRequest')

- script: dotnet nuget push --api-key AzureArtifacts --source https://pkgs.dev.azure.com/saucecontrol/InheritDoc/_packaging/inheritdoc_ci/nuget/v3/index.json out\bin\InheritDoc\Dist\SauceControl.InheritDoc.*.nupkg
  displayName: Push
  condition: ne(variables['Build.Reason'], 'PullRequest')

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: out\testresults\*.trx
