trigger:
- master

pool:
  vmImage: windows-latest

name: $(Year:yy)$(DayOfYear)$(Rev:r)
steps:
- task: NuGetAuthenticate@0
  condition: ne(variables['Build.Reason'], 'PullRequest')

- task: UseDotNet@2
  displayName: Ensure 3.1 SDK
  inputs:
    version: 3.1.x
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: Ensure 2.1 Runtime
  inputs:
    packageType: runtime
    version: 2.1.x
    performMultiLevelLookup: true

- script: dotnet build src\InheritDoc -c Release --version-suffix ci$(Build.BuildNumber)
  displayName: Build

- script: dotnet test tests\InheritDoc.Test -c Release
  displayName: Test

- script: dotnet nuget push --api-key AzureArtifacts --source https://pkgs.dev.azure.com/saucecontrol/InheritDoc/_packaging/inheritdoc_ci/nuget/v3/index.json out\bin\InheritDoc\Release\SauceControl.InheritDoc.*.nupkg
  displayName: Push
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
