trigger:
- master

pool:
  vmImage: windows-latest

name: $(Year:yy)$(DayOfYear)$(Rev:r)
steps:
- task: UseDotNet@2
  displayName: Ensure 3.1 SDK
  inputs:
    version: 3.1.x
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: Ensure 2.1 Runtime
  inputs:
    packageType: runtime
    version: 2.1.x
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'src/**/*.csproj'
    arguments: '-c Release --version-suffix ci$(Build.BuildNumber)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'tests/**/*.csproj'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Push
  inputs:
    command: push
    packagesToPush: 'out/bin/**/*.nupkg'
    nuGetFeedType: internal
    publishVstsFeed: dd014012-9652-4bcb-ab13-4246c21ac23d/d8fa8e21-ef37-4a2b-a7d6-795faf41e3be
